### PR TITLE
[Breaks 18] update xplayer-plugins dependency on Python 2 loader

### PR DESCRIPTION
**Pull request by monsta**
the loader package in Ubuntu 18.04 and Debian Stretch has a new name

### CODE REVIEW

**Comment by clefebvre** [comment]
@monsta you can't break the build for Mint 18 yet. You need to use this instead:

libpeas-1.0-python2loader | libpeas-1.0-0-python2loader

**Comment by monsta** [comment]
Well, no problem, you can merge it after builds for Mint 18 won't be needed in master.

**Comment by clefebvre** [comment]
If you fix it I can merge it right now.

**Comment by clefebvre** [comment]
It's actually ok as it is. There's a virtual package in stretch which does the job.

**Pull request closed without merging**
