### PR TITLE
Renamed Movie menu to File

### PR DESCRIPTION
**Pull request by RavetcoFX**
For consistency with other apps

### CODE REVIEW

**Comment by Windsurfer01** [comment]
I agree. Audio files are not movie files, so 'File' is much better.

**Comment by clefebvre** [comment]
Should it be _File?

**Comment by RavetcoFX** [comment]
I don't think so, as apps like Xed and Xreader use "File"

**Comment by clefebvre** [comment]
so you can't open it with Alt+F?

**Comment by clefebvre** [comment]
https://github.com/linuxmint/xplayer/commit/ce3f19cac08c4b2a032145c78fa10d7c84e21b0e

**Pull request closed without merging**
