### PR TITLE
Left click on video to pause/resume (fix #134)

### LINKED ISSUE #134: Feature request: Click to pause/resume
Not an issue but a request.

On Youtube for example, clicking on the video can stop it, and clicking on it again resume the video.
There's an [addon for VLC](https://github.com/nurupo/vlc-pause-click-plugin) also which implemented it.

I found it personally very handy.
Other people interested?

### PR DESCRIPTION
**Pull request by SergiusTheBest**
This PR adds pause/resume playback using left click on a video.

### CODE REVIEW

**Comment by clefebvre** [comment]
It's a convenient to quickly play/pause but it gets in the way of double-clicking to switch to and from fullscreen mode. The way it works right now is consistent with VLC, MPV, Totem etc..

**Comment by SergiusTheBest** [comment]
@clefebvre It doesn't break double click functionality.
> The way it works right now is consistent with VLC, MPV, Totem etc..

Yes, but we can be better than they are. Click to pause is very expected by a user nowadays. If you are still not convinced what about making it configurable?

**Comment by clefebvre** [comment]
It doesn't "break" double-click, I didn't phrase that correctly. It gets in the way when you double-click to make it fullscreen, it pauses/resumes it, so it feels buggy.

We can pause easily with the space bar, the OSD and the right-click menu.

Pretty much any idea can be turned into an option and made configurable. I don't think it should be a matter of taste, we're not making a meta-player people can mod any way they want. It makes a lot of sense to click to pause on a smartphone when fullscreen is always on, but here I'm not sure it does.

**Comment by NathanC** [comment]
I would only want to make something full screen as an occasional action, I would want to pause/resume as a common action.

A right click menu for full screen makes more sense than a right click menu for pause. All major browser players I've seen (YouTube, Netflix, Hulu, etc) have pause to click, and like  @SergiusTheBest said it's an expected feature for most users.

**Pull request closed without merging**
